define({  
    map: {
      error: "Krijimi i hartës i pamundur"
    },
    onlineStatus: {
      offline: "Për momentin nuk keni rrjet. Kërkesat do të ruhen derisa të ktheheni në rrjet.",
      reconnecting: "Duke u rikyqur&hellip;",
      pending: "${total} ndryshimet në pritje do të kryhen pas rikyqjes në rrjet."
    },
    configure: {
      mapdlg: {
        items: {
          organizationLabel: "Organizata ime",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Përmbajtja ime",
          favoritesLabel: "Përmbajtja ime e preferuar"
        },
        title: "Zgjedh hartën",
        searchTitle: "Kërko",
        ok: "Në rregull",
        cancel: "Anulo",
        placeholder: "Shkruaj fjalën për kërkim"
      },
      groupdlg: {
        items: {
          organizationLabel: "Organizata ime",
          onlineLabel: "ArcGIS Online",
          contentLabel: "Përmbajtja ime",
          favoritesLabel: "Përmbajtja ime e preferuar"
        },
        title: "Zgjedh grupin",
        searchTitle: "Kërko",
        ok: "Në rregull",
        cancel: "Anulo",
        placeholder: "Shkruaj fjalën për kërkim"
      },
      sharedlg: {
        items: {},
        mailtoLinkDescription: "Këtu gjendet linku per aplikacionin Geoform"
      }
    },
    user: {
      all: "Të gjitha",
      mgrs: "MGRS",
      usng: "USNG",
      utm: "UTM",
      utm_northing: "Northing",
      utm_easting: "Easting",
      utm_zone_number: "Numri i zonës",
      selectLayerTabText: "${formSection} Zgjedh Formularin",
      geoFormGeneralTabText: "${formSection} Fut Informacionin",
      locationInformationText: "${formSection} Zgjedh Vendndodhjen",
      submitInformationText: "${formSection} Kompleto Kërkesën",
      submitInstructions: "Shto këtë informatë në hartë.",
      myLocationText: "Vendndodhja e tanishme",
      locationDescriptionForMoreThanOneOption: "Specifiko lokacionin për këtë shënim duke klikuar/prekur hartën ose duke përdorur njëren nga opcionet e mëposhtme.",
      locationDescriptionForOneOption: "Specifiko lokacionin për këtë shënim duke klikuar/prekur hartën ose duke përdorur opcionin e mëposhtëm.",
      locationDescriptionForNoOption: "Specifiko lokacionin për këtë shënim duke klikuar/prekur hartën.",
      addressText: "Kërko",
      geographic: "Gjer./Gjat.",
      locationTabText: "Lokacioni",
      locationPopupTitle: "Lokacioni",
      submitButtonText: "Dërgo Kërkesësn",
      submitButtonTextLoading: "Duke dërguar&hellip;",
      formValidationMessageAlertText: "Fushat në vijim janë të domosdoshme:",
      selectLocation: "Zgjedh lokacionin për kërkesën tënde.",
      emptylatitudeAlertMessage: "Fut koordinatat e ${openLink}gjerësisë gjeografike${closeLink}.",
      emptylongitudeAlertMessage: "Fut koordinatat e ${openLink}gjatësisë gjeografike${closeLink}.",
      shareUserTitleMessage: "Faleminderit për kontributin tuaj!",
      entrySubmitted: "Kërkesa juaj është vendosur në hartë.",
      shareThisForm: "Shpërndaje këtë Formular",
      shareUserTextMessage: "Tregoju të tjerëve të kontribuojnë duke përdorur opcionet e mëposhtme.",
      addAttachmentFailedMessage: "Vendosja e shtojcës në shtresë e pamundur",
      addFeatureFailedMessage: "Vendosja e gjeoobjektit në shtresë e pamundur",
      noLayerConfiguredMessage: "Ka ndodhur një gabim gjatë vendosjes apo kërkimit të shtresës. Për të shfaqur formularin dhe për të filluar pranimin e kërkesave, shto një shtresë në web hartë.",
      placeholderLatitude: "Gjerësia gjeografike (Y)",
      placeholderLongitude: "Gjatësia gjeografike (X)",
      latitude: "Gjerësia gjeografike",
      longitude: "Gjatësia gjeografike",
      findMyLocation: "Ma përcakto vendndodhjen",
      finding: "Përcaktimi i vendndodhjes&hellip;",
      backToTop: "Kthehu në fillim",
      addressSearchText: "Kërkesa juaj do të shfaqet këtu. Mund ta lëvizni pikën për ta korrigjuar vendndodhjen.",
      shareModalFormText: "Linku i formularit",
      close: "Mbyll",
      locationNotFound: "Gjetja e lokacionit e pamundur.",
      setLocation: "Cakto lokacionin",
      find: "Gjej adresen apo vendin",
      attachment: "Shtojca",
      toggleDropdown: "Ndez/Fike listen",
      invalidString: "Shkruaj vlerën valide.",
      invalidSmallNumber: "Shkruaj vlerën valide ${openStrong}të numrit${closeStrong} në mes -32768 dhe 32767.",
      invalidNumber: "Shkruaj vlerën valide ${openStrong}të numrit${closeStrong} në mes -2147483648 dhe 2147483647.",
      invalidFloat: "Shkruaj vlerën valide ${openStrong}të pikës${closeStrong}.",
      invalidDouble: "Shkruaj vlerën valide ${openStrong}të numrit${closeStrong}.",
      invalidLatLong: "Shkruaj koordinatat valide të gjerësisë dhe gjatësisë gjeografike.",
      invalidUTM: "Shkruaj koordinatat valide UTM.",
      invalidUSNG: "Shkruaj koordinatat valide USNG.",
      invalidMGRS: "Shkruaj koordinatat valide MGRS.",
      geoformTitleText: "GeoForm",
      domainDefaultText: "Zgjedh&hellip;",
      applyEditsFailedMessage: "Ka ndodhur një gabim gjatë dërgimit.",
      applyEditsFailedRobot: "Dërgimi është refuzuar sepse ka dështuar gjatë detektimit të robotit.",
      applyEditsAuthError: "Kërkesa juaj nuk mund të dërgohet për shkak të llojit të nivelit të përdoruesit. Kontakto administratorin e organizatës tuaj për asistencë.",
      requiredFields: "Fusha në vijim është e domosdoshme. Shkruaj të dhëna valide.",
      requiredField: "(domosdoshme)",
      error: "Gabim",
      textRangeHintMessage: "${openStrong}Përkujtues:${closeStrong} Vlera minimale ${minValue} dhe vlera maksimale ${maxValue}",
      dateRangeHintMessage: "${openStrong}Përkujtues:${closeStrong} Data minimale ${minValue} dhe data maksimale ${maxValue}",
      remainingCharactersHintMessage: "${value} shkronjat e mbetura",
      mapFullScreen: "Ekran i plotë",
      mapRestore: "Kthe",
      filterSelectEmptyText: "Zgjedh",
      invalidLayerMessage: "Nuk është gjetur shtresa valide për krijimin e Gjeoformës. Nëse Gjeoforma është konfiguruar me një shtresë, shtresa nuk është më në dispozicion, ose autorizimi ka dështuar.",
      selectedLayerText: "Të gjitha",
      fileUploadStatus: "Statusi i ngarkimit të skedarit",
      uploadingBadge: "&nbsp;Ngarkimi&hellip;",
      successBadge: "&nbsp;Ngarkuar",
      retryBadge: "Provo përsëri",
      errorBadge: "Gabim gjatë ngarkimit&nbsp;&nbsp;&nbsp;",
      fileTooLargeError: "Skedari shumë i madh për t'u shtuar",
      exceededFileCountError: "Është tejkaluar numri i lejuar i shtojcave",
      selectFileTitle: "Zgjedh skedarin",
      btnSelectFileText: "Zgjedh skedarin",
      btnViewSubmissions: "Shiqo kërkesat"
    },
    builder: {
      gettingStarted: "Fillimi",
      dateSettings: "Rregullimi i datës",
      hiddenDateField: "Fshehe fushën e datës",
      preventPastDates: "Parandalo datat e kaluara",
      preventFutureDates: "Parandalo datat e ardhshme",
      useCurrentDate: "Vendose këtë fushë me datët dhe kohën e tanishme",
      configure: "Konfiguro",
      configureField: "Fusha e konfigurimit '${fieldName}'",
      invalidUser: "Më vjen keq, nuk lejohet të shikoni këtë artikull",
      invalidWebmapSelectionAlert: "Web harta e zgjedhur nuk përmban shtresë valide për përdorim. Ju lutem shtoni një shtresë në web hartë për të vazhduar.",
      invalidWebmapSelectionAlert2: "Për më shumë informata referohuni te ${openLink}Çka është shtresa?${closeLink}",
      selectFieldsText: "Zgjedh fushat e kërkesës",
      selectThemeText: "Zgjedh temën e kërkesës",
      setViewerText: "Konfiguro formularin",
      introText: "Fillo",
      webmapText: "Web harta",
      layerText: "Shtresa",
      detailsText: "Detalet",
      fieldsText: "Fushat",
      styleText: "Stili",
      viewerText: "Pamja",
      optionText: "Opcionet",
      previewText: "Inspekto",
      publishText: "Publiko",
      optionsApplicationText: "Opcionet",
      submitButtonText: "Teksti i butonit për dërgim (Opcional)",
      submitButtonDesc: "Etiketo butonin për dërgim. Ky tekst nuk do të përkthehet.",
      viewSubmissionsText: "Shih tekstin e dërgimit (Opcional)",
      viewSubmissionsDesc: "Etiketo butonin për t'i parë kërkesat. Ky tekst nuk do të përkthehet.",
      titleText: "Ndërtuesi",
      descriptionText: "GeoForm është një shabllon i konfigurueshëm për editimin e të dhënave të një ${link1}Shtrese${closeLink}. Ky aplikacion i lejon përdoruesit të fusin të dhëna përmes një formulari derisa shfrytëzon fuqinë e ${link2}Web hartës${closeLink} dhe shtresës edituese. Përdor hapat në vijim për të rregulluar dhe vendosur GeoForm.",
      btnPreviousText: "Paraprak",
      btnNextText: "Pasues",
      webmapTabTitleText: "Zgjedh web hartën",
      viewWebmap: "Shiko web hartën",
      webmapDetailsText: "Web harta e zgjedhur është ${webMapTitleLink}${webMapTitle}${closeLink}. Për të zgjedhur web hartën tjetër kliko në butonin 'Zgjedh Web Hartën'",
      btnSelectWebmapText: "Zgjedh web hartën",
      btnSelectWebmapTextLoading: "Duke ngarkuar&hellip;",
      layerTabTitleText: "Zgjedh shtresen edituese",
      selectLayerLabelText: "Shtresa",
      selectLayerDefaultOptionText: "Zgjedh shtresën",
      enableBasemapToggle: "Shfaq hartat bazë",
      enableBasemapToggleDescription: "Mund ta konfiguroni GeoForm të Shfaq/Fsheh hartat bazë",
      defaultBasemap: "Hartat bazë",
      secondaryBasemap: "Harta bazë e parazgjedhur",
      detailsTabTitleText: "Detalet e formularit",
      detailTitleLabelText: "Titulli",
      detailLogoLabelText: "Llogo",
      descriptionLabelText: "Udhëzimet e formularit & detalet",
      fieldDescriptionLabelText: "Teksti i ndihmës (opcional)",
      fieldDescriptionHelpText: "Shkruaj një përshkrim apo udhëzim për këtë fushë.",
      fieldHintHelpText: "Vendi i tekstit për fushë.",
      fieldTabFieldHeaderText: "Fusha",
      fieldTabLabelHeaderText: "Etiketa",
      fieldTabDisplayTypeHeaderText: "Shfaq si",
      fieldTabOrderColumnText: "Renditje",
      fieldTabVisibleColumnText: "Aktivizuar",
      displayFieldText: "Shfaq fushën",
      selectMenuOption: "Zgjedh menynë",
      selectRadioOption: "Radio butoni",
      selectTextOption: "Teksti",
      selectDateOption: "Zgjedhësi i datës",
      selectRangeOption: "Flutura",
      selectCheckboxOption: "Kutia",
      selectMailOption: "Email adresa",
      selectUrlOption: "URL",
      selectTextAreaOption: "Zona e tekstit",
      previewApplicationText: "Inspekto aplikacionin",
      saveApplicationText: "Ruaj aplikacionin",
      saveText: "Ruaj",
      toggleNavigationText: "Navigacioni",
      formPlaceholderText: "Formulari im",
      shareBuilderInProgressTitleMessage: "Publikimi i Geoform",
      shareBuilderProgressBarMessage: "Ju lutem prisni&hellip;",
      shareBuilderTitleMessage: "Sukses! E ruajtur",
      shareBuilderTextMessage: "Mund të mbledhni informata duke e shpërndar me të tjerët",
      shareModalFormText: "Linku i formularit",
      shareBuilderSuccess: "GeoForm është përditësuar dhe publikuar!",
      geoformTitleText: "Geo Form",
      layerTabText: "Kjo është shtresa nga e cila do të ndërtohet GeoForm. Shtresa duhet të jetë e editueshme me lejen përkatëse të shpërndarjes për audiencen e juaj.",
      detailsTabText: "Përdor detalet e formularit për të rregulluar titullin, shto një llogo, dhe bëj një përshkrim të shkurtër për audiencën e GeoForm. Në përshkrim mund të shtoni link, informata kontaktimi, etj.",
      fieldsTabText: "Këtu mund të zgjedhni cilat fusha do të jenë të dukshme për audiencën e GeoForm, dhe shtoni një përshkrim.",
      styleTabText: "Stili i GeoForm sipas preferencave tuaja.",
      viewerTabText: "Vendos opcionin për shikimin e kërkesave të dërguara përmes GeoForm.",
      publishTabText: "Nëse keni përfunduar me përshtatjen e GeoForm, ruaje aplikacionin dhe shpërndaje me audiencen tuaj.",
      headerSizeLabel: "Madhësia e shkronjave",
      smallHeader: "Përdor shkronjat e vogla",
      bigHeader: "Përdor shkronjat e mëdha",
      pushpinText: "Pika shtytëse",
      doneButtonText: "Ruaj dhe Mbyll",
      fieldTabPlaceHolderHeaderText: "Aluzion teksti (opcional)",
      enableAttachmentLabelText: "${openStrong}Mundëso shtojcën${closeStrong}",
      enableAttachmentLabelHint: "Këtu mund ta mundësoni/pamundësoni shtojcën",
      attachmentIsRequiredLabelText: "${openStrong}Shtojca e domosdoshme${closeStrong}",
      attachmentIsRequiredLabelHint: "Nqs është e domosdoshme, përdoruesit mund të bashkëngjesin një shtojcë.",
      attachmentLabelText: "Butoni i shtojcës",
      attachmentLabelHint: "Ky tekst do të shfaqet te butoni i shtojcës. Këtu mund të përshkruani çka do dëshironit audienca të bashkangjes (foto, video, dokument, etj.), formatin e skedarit që po e kërkoni (.jpeg, .png, .docx, .pdf, etj.), dhe çdo udhëzim tjetër",
      attachmentDescription: "Përshkrimi i shtojcës",
      attachmentHint: "Nqs është e domosdoshme, këtu mund të vendosni informata shtesë për shtojcën.",
      jumbotronDescription: "Përdor shkronjat e mëdha apo të vogla në formularin tuaj. Titulli i madh mund të ndihmoj në definimin e qëllimit të aplikacionit por zë më shumë vend në ekran",
      shareGeoformText: "Butoni i mediave sociale",
      shareDescription: "Butoni i mediave sociale iu lejon audiencës tuaj lehtësisht shpërndarjen e GeoForm pasi ata ta kenë bërë kërkesën",
      defaultMapExtent: "Shtrirja e hartës",
      defaultMapExtentDescription: "Harta do të vendoset në shtrirjen e zakonshme pas dërgimit - kjo mund të pamundësohet në çdo kohë.",
      pushpinOptionsDescription: "Zgjedh ngjyren për pikën, ajo duhet të jetë e ndryshme nga simbologjia e hartës për të ndihmuar përdoruesin ta vendos në hartë",
      selectLocationText: "Zgjedh vendndodhjen sipas",
      myLocationText: "Vendndodhja ime",
      searchText: "Kërko",
      coordinatesText: "Kordinatat e gjerësisë & gjatësisë gjeografike",
      usng: "Kordinatat USNG",
      mgrs: "Kordinatat MGRS",
      utm: "Kordinatat UTM",
      selectLocationSDescription: "Lejo përdoruesit ta zgjedhin vendndodhjen duke përdorur këto metoda.",
      dragTooltipText: "Tërheq fushën aty ku dëshiron të shfaqet",
      showHideLayerText: "Shfaq shtresën",
      showHideLayerHelpText: "Mund ta konfiguroni GeoForm të Shfaq/Fsheh shtresën. Ky opcion aplikohet vetëm për një shtresë.",
      enableOfflineSupport: "Mundëso përkrahjen pa rrjet",
      enableOfflineSupportHelpText: "Ruaji kërkesat kur nuk ka rrjet dhe dërgoji ato kur të bëhet rikyqja në rrjet.",
      labelHelpMessage: "Etiketa",
      placeHolderHintMessage: "Aluzion teksti",
      placeHolderHelpMessage: "Aluzion teksti",
      selectTextOptionValue: "Filtro zgjedhjen",
      disableLogo: "Pamundëso llogon",
      disableLogoDescription: "Konfiguro GeoForm të Shfaq/Fsheh llogon",
      locateOnLoadText: "Përcakto vendndodhjen gjatë hapjes",
      locateOnLoadDescription: "Mund ta konfiguroni GeoForm ta përdor vendndodhjen e tanishme gjatë hapjes së faqes",
      selectLayerFieldTabText: "Zgjedh shtresën",
      allLayerSelectOptionText: "Të gjitha shtresat",
      disableViewer: "Pamundëso inspektuesin",
      disableViewerDescription: "Mund ta konfiguroni GeoForm të Shfaq/Fsheh inspektuesin",
      displayFieldHintText: "Fushat e zgjedhura do të shfaqen si titull te inspektuesi"
    },
    viewer: {
      geocoderCancelText: "Anulo",
      viewMapTabText: "Harta",
      sortHeaderText: "Rendit sipas:",
      geocoderPlaceholderText: "Kodi postal, qyteti, etj.",
      noSearchResult: "Nuk u gjet rezultat",
      legendTabTooltip: "Legjenda",
      aboutUsTabTooltip: "Rreth nesh",
      mapTabTooltip: "Harta",
      btnDescendingText: "Zbrit",
      btnAscendingText: "Ngrit",
      geometryUnavailableErrorMessage: "Gabim në gjetjen e gjeometrisë",
      infoPopupOffErrorMessage: "Nuk ka informatë për të shfaqur",
      btnLoadMoreText: "Ngarko më shumë",
      unavailableTitleText: "Patitulluar",
      unavailableConfigMessage: "E pamundur të ngarkohet konfigurimi",
      share: "Shpërndaj",
      viewReportsTabText: "Raportet",
      viewLegendTabText: "Legjenda",
      viewAboutusTabText: "Rreth",
      appLoadingFailedMessage: "Gabim në ngarkimin e inspektuesi"
    }  
});
